[package]
name = "jemini"
license = "MIT"
version = "0.1.0"
edition = "2021"
publish = true
description = "TBC"
authors = ["jer"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
